export const API = 'http://localhost:3001';

// LOGIN
export const LOG_IN = 'LOG_IN'
export const LOGGED_IN = 'LOGGED_IN';
export const LOGGIN_FAILED = 'LOGGIN_FAILED';

// logout
export const LOG_OUT = 'LOG_OUT';

// FILE UPLOAD
export const FILE_UPLOADED = 'FILE_UPLOADED';
export const FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED';

// FETCH FILES
export const FETCH_FILES_SUCCESS = 'FETCH_FILES_SUCCESS';
export const FETCH_FILES_FAILED = 'FETCH_FILES_FAILED';

// UNZIP FILES
export const FILE_UNZIPED = 'FILE_UNZIPED';
export const FILE_UNZIP_FAILED = 'FILE_UNZIP_FAILED';

// SET UNIT
export const SET_UNIT = 'SET_UNIT';

// document actions
export const STATUS_TO_INFO_CHANGED = 'STATUS_TO_INFO_CHANGED'
export const STATUS_TO_INFO_FAILED = 'STATUS_TO_INFO_FAILED'
export const STATUS_TO_CHANGED = 'STATUS_TO_CHANGED'
export const STATUS_CHANGE_FAILED = 'STATUS_CHANGE_FAILED'
export const MINUTES_OF_MEETING_ADDED = 'MINUTES_OF_MEETING_ADDED'
export const MINUTES_OF_MEETING_FAILED = 'MINUTES_OF_MEETING_FAILED'


// unit dashboard
export const UNIT_DASHBOARD_RECEIVED = 'UNIT_DASHBOARD_RECEIVED';
export const UNIT_DASHBOARD_FAILED = 'UNIT_DASHBOARD_FAILED'

// organizer and presenter dashboard
export const ORGANIZER_DASHBOARD_RECEIVED = 'ORGANIZER_DASHBOARD_RECEIVED';
export const ORGANIZER_DASHBOARD_FAILED = 'ORGANIZER_DASHBOARD_FAILED';

// UPDATE FILE
export const FILE_UPDATED = 'FILE_UPDATED'
export const FILE_UPDATE_FAILED = 'FILE_UPDATE_FAILED'

// CHART PER UNIT
export const BUSINESS_CHART_ARIVED = 'BUSINESS_CHART_ARIVED'
export const IT_CHART_ARIVED = 'IT_CHART_ARIVED'
export const HR_CHART_ARIVED = 'HR_CHART_ARIVED'
export const WHOLESALE_CHART_ARIVED = 'WHOLESALE_CHART_ARIVED'
export const FINANCE_CHART_ARIVED = 'FINANCE_CHART_ARIVED'


export const BUSINESS_CHART_FAILED = 'DASHBOARD_CHART_FAILED'
export const IT_CHART_FAILED = 'IT_CHART_FAILED'
export const HR_CHART_FAILED = 'HR_CHART_FAILED'
export const WHOLESALE_CHART_FAILED = 'WHOLESALE_CHART_FAILED'
export const FINANCE_CHART_FAILED = 'FINANCE_CHART_FAILED'

// fail
export const DASHBOARD_CHART_UNIT_FAILED = 'DASHBOARD_CHART_UNIT_FAILED'

// cancel document edit
export const CLOSE_DOCUMENT_EDIT = 'CLOSE_DOCUMENT_EDIT'